"""Where uploaded documents live on disk. Paths are generated by the server; a student's filename is only ever
a display label and never part of a filesystem path."""
import re
import uuid
from pathlib import Path

from app.config import settings

TYPES = {"pdf": "PDF", "txt": "text", "md": "Markdown"}


def max_bytes() -> int:
    return int(settings.max_doc_mb * 1024 * 1024)


def root() -> Path:
    return Path(settings.upload_dir).resolve()


def display_name(original: str | None) -> str:
    """Basename only, control characters removed, length capped."""
    name = re.split(r"[\\/]", original or "")[-1]
    name = re.sub(r"[\x00-\x1f\x7f]", "", name).strip().strip(".")
    return name[:200] or "document"


def sniff_type(name: str, data: bytes) -> str | None:
    """Real type from content (PDF magic bytes), falling back to the extension only for text files."""
    if data.lstrip()[:5] == b"%PDF-" or data[:5] == b"%PDF-":
        return "pdf"
    if b"\x00" in data[:4096]:
        return None  # binary content pretending to be text
    ext = name.rsplit(".", 1)[-1].lower() if "." in name else ""
    return ext if ext in ("txt", "md") else None


def save(user_id: int, data: bytes, file_type: str) -> str:
    rel = Path("documents") / str(user_id) / f"{uuid.uuid4().hex}.{file_type}"
    dest = root() / rel
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_bytes(data)
    return rel.as_posix()


def resolve(rel: str | None) -> Path | None:
    if not rel:
        return None
    path = (root() / rel).resolve()
    return path if path.is_relative_to(root()) else None


def read(rel: str | None) -> bytes | None:
    path = resolve(rel)
    try:
        return path.read_bytes() if path and path.is_file() else None
    except OSError:
        return None


def delete(rel: str | None) -> None:
    path = resolve(rel)
    try:
        if path and path.is_file():
            path.unlink()
    except OSError:
        pass  # best effort; the database row is the source of truth
